INSERT INTO PRODUCT_CATEGORIES (ID,NAME) VALUES(1,'toys');
INSERT INTO PRODUCT_CATEGORIES (ID,NAME) VALUES(2,'electronics');
INSERT INTO PRODUCT_CATEGORIES (ID,NAME) VALUES(3,'art');
INSERT INTO PRODUCT_CATEGORIES (ID,NAME) VALUES(4,'music');
INSERT INTO PRODUCT_CATEGORIES (ID,NAME) VALUES(5,'apparel');
INSERT INTO PRODUCT_CATEGORIES (ID,NAME) VALUES(6,'jewelry');